language: python
python:
  - "3.8"
install:
  - pip install -r requirements-test.txt
  - pip install pytest-cov
  - pip install coveralls
script:
  py.test --cov-report= --cov=rest_framework_ccbv tests/
after_success:
  coveralls
